trigger:
  branches:
    include:
      - main
      - feature-branch

pool:
  name: 'My pipeline Agent'

steps:

- checkout: self

- script: terraform --version
  displayName: 'Check Terraform Version'

- script: terraform init
  displayName: 'Terraform Init'
  workingDirectory: '$(Build.SourcesDirectory)/my_parent_module'

- script: terraform fmt -check
  displayName: 'Terraform Format Check'
  workingDirectory: '$(Build.SourcesDirectory)/my_parent_module'

- script: terraform validate
  displayName: 'Terraform Validate'
  workingDirectory: '$(Build.SourcesDirectory)/my_parent_module'

- powershell: |
    @'
    my_kaju1 = {
      this-rg1 = {
        name     = "my-kaju"
        location = "Central India"
      }
    }
    '@ | Set-Content terraform.auto.tfvars

    terraform plan
  displayName: 'Terraform Plan'
  workingDirectory: '$(Build.SourcesDirectory)/my_parent_module'