```yaml
trigger:
  branches:
    include:
      - main
      - feature-branch

pool:
  name: 'My pipeline Agent'

steps:

# Checkout Code
- checkout: self

# Download terraform.tfvars
- task: DownloadSecureFile@1
  name: tfvars
  displayName: 'Download Terraform Variables'
  inputs:
    secureFile: 'terraform.tfvars'

# Copy terraform.tfvars
- powershell: |
    Copy-Item "$(tfvars.secureFilePath)" "$(Build.SourcesDirectory)\my_parent_module\terraform.tfvars" -Force
  displayName: 'Copy Terraform Variables'

# Verify terraform.tfvars
- powershell: |
    Write-Host "Checking terraform.tfvars..."

    if (Test-Path "$(Build.SourcesDirectory)\my_parent_module\terraform.tfvars") {
        Write-Host "terraform.tfvars EXISTS"

        Write-Host "Checking required variables..."
        Get-Content "$(Build.SourcesDirectory)\my_parent_module\terraform.tfvars" |
          Select-String "^(vnet2|stg)"
    }
    else {
        Write-Error "terraform.tfvars NOT FOUND"
    }
  displayName: 'Verify Terraform Variables'

# Terraform Version
- script: terraform --version
  displayName: 'Terraform Version'

# Terraform Init
- script: terraform init
  displayName: 'Terraform Init'
  workingDirectory: '$(Build.SourcesDirectory)/my_parent_module'

# Terraform Format Check
- script: terraform fmt -check
  displayName: 'Terraform Format Check'
  workingDirectory: '$(Build.SourcesDirectory)/my_parent_module'

# Terraform Validate
- script: terraform validate
  displayName: 'Terraform Validate'
  workingDirectory: '$(Build.SourcesDirectory)/my_parent_module'

# TFLint
- script: tflint
  displayName: 'TFLint'
  workingDirectory: '$(Build.SourcesDirectory)/my_parent_module'

# Checkov
- powershell: |
    $env:Path += ";C:\Users\gaura\AppData\Local\Python\pythoncore-3.14-64\Scripts"
    checkov -d .
  displayName: 'Checkov'
  workingDirectory: '$(Build.SourcesDirectory)/my_parent_module'

# Terraform Plan
- script: terraform plan -var-file="terraform.tfvars"
  displayName: 'Terraform Plan'
  workingDirectory: '$(Build.SourcesDirectory)/my_parent_module'
```
